// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7TRz1ebEBWgfVKIbLgShekPgZHNDb2YA',
    appId: '1:338622948818:web:3a9554c3ba40cee0cb540b',
    messagingSenderId: '338622948818',
    projectId: 'track2drive-dev',
    authDomain: 'track2drive-dev.firebaseapp.com',
    storageBucket: 'track2drive-dev.firebasestorage.app',
    measurementId: 'G-2RR410LECD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGyGnXRO8062fEsaA4hgG_vIVfyPnrsiQ',
    appId: '1:338622948818:android:16393a0898823addcb540b',
    messagingSenderId: '338622948818',
    projectId: 'track2drive-dev',
    storageBucket: 'track2drive-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEvu-vVzS01lP8soOIAuK6fOKkB4qVLvM',
    appId: '1:338622948818:ios:12354a127187686acb540b',
    messagingSenderId: '338622948818',
    projectId: 'track2drive-dev',
    storageBucket: 'track2drive-dev.firebasestorage.app',
    iosBundleId: 'de.rentrop.track2drive.dev',
  );
}
